In [1]:
import numpy as np, pandas as pd
from keras.datasets import mnist
from os import path, getcwd

CWD = getcwd()

In [2]:
DATA_DIR = path.join(CWD, "data")

(x_train, y_train), (x_test, y_test) = mnist.load_data(path=path.join(DATA_DIR, "mnist"))

In [3]:
x_train = x_train / 255
x_test = x_test / 255

In [4]:
x_train = x_train.reshape(-1, 784).T
x_test = x_test.reshape(-1 ,784).T

m, n = x_train.shape
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [7]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [8]:
W1, b1, W2, b2 = gradient_descent(x_train, y_train, 0.10, 500)

Iteration:  0
[1 7 1 ... 1 1 1] [5 0 4 ... 5 6 8]
0.08501666666666667
Iteration:  10
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  20
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  30
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  40
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  50
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  60
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  70
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  80
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  90
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  100
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  110
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  120
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  130
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  140
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  150
[9 9 9 ... 9 9 9] [5 0 4 ... 5 6 8]
0.09915
Iteration:  160
[9 9 9 ... 9 9 9] [5 0 

KeyboardInterrupt: 